server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://localhost:9001
          predicates: [ Path=/auth/** ]
        - id: permission
          uri: http://localhost:9002
          predicates: [ Path=/permissions/** ]
