CREATE TABLE IF NOT EXISTS sys_user (id BIGINT PRIMARY KEY AUTO_INCREMENT, username VARCHAR(64) UNIQUE NOT NULL, password_hash VARCHAR(255) NOT NULL, status TINYINT NOT NULL DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS sys_role (id BIGINT PRIMARY KEY AUTO_INCREMENT, code VARCHAR(64) UNIQUE NOT NULL, name VARCHAR(64) NOT NULL, parent_id BIGINT NULL, status TINYINT NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS sys_permission (id BIGINT PRIMARY KEY AUTO_INCREMENT, code VARCHAR(128) UNIQUE NOT NULL, name VARCHAR(128) NOT NULL, type VARCHAR(16) NOT NULL, resource VARCHAR(255), action VARCHAR(32), status TINYINT NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS sys_user_role (user_id BIGINT NOT NULL, role_id BIGINT NOT NULL, PRIMARY KEY(user_id,role_id));
CREATE TABLE IF NOT EXISTS sys_role_permission (role_id BIGINT NOT NULL, permission_id BIGINT NOT NULL, PRIMARY KEY(role_id,permission_id));
CREATE TABLE IF NOT EXISTS sys_role_conflict (role_id BIGINT NOT NULL, conflict_role_id BIGINT NOT NULL, PRIMARY KEY(role_id,conflict_role_id));
CREATE TABLE IF NOT EXISTS sys_audit_log (id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT, event_type VARCHAR(32) NOT NULL, detail JSON, ip VARCHAR(64), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, INDEX idx_audit_user(user_id));
